// app/(auth)/(route)/register/components/VerifyAccount.tsx
// 'use client'

import React, { FunctionComponent, InputHTMLAttributes, useState } from 'react';
import { InputOtp } from 'primereact/inputotp';
import { Button } from 'primereact/button';

import styles from './styles.module.scss'
import '../../globals.css';

import { SubmitOTP } from './actions';

interface CustomInputProps extends InputHTMLAttributes<HTMLInputElement> {
    events: any;
    props: any;
}

export default function VerifyAccount(props: {email: string}) {
    const [token, setTokens] = useState<string>('');

    const otpChange = () => {
        SubmitOTP(token, props.email)
    }

    return (
        <form action={otpChange} className="card flex flex-row justify-center">
            <div className="flex flex-col gap-3 my-10 items-center">
                <p className="font-bold text-4xl mb-2">Authenticate Your Account</p>
                <p className="text-color-secondary block mb-5">Please enter the code sent to your phone.</p>
                <InputOtp name='otp' length={6} value={token} onChange={(e) => setTokens(e.value)} integerOnly/>
                
                {/* <InputOtp name='otp' length={6} integerOnly/> */}

                <div className={` flex w-full justify-between mt-5 item-stretch justify-items-stretch`}>
                    <Button  label="Resend Code" link className="p-0 button"></Button>
                    <Button type="submit" label="Submit Code"></Button>
                </div>
            </div>
        </form>
    );
}

// src/app/register/verify-account/verify-account.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-verify-account',
  standalone: true,
  imports: [],
  templateUrl: './verify-account.component.html',
  styleUrl: './verify-account.component.scss'
})
export class VerifyAccountComponent {

}

<!-- <div class="card flex justify-center">
    <p-inputotp [(ngModel)]="otp" />
</div> -->

<div class="card flex justify-center h-full">
    <div class="flex flex-col items-center">
        <div class="font-bold text-xl mb-2">Authenticate Your Account</div>
        <p class="text-muted-color block mb-8">Please enter the code sent to your email.</p>
        <p-inputotp [(ngModel)]="otp" size="large" [length]="6" />
        <div class="flex justify-between mt-8 self-stretch">
            <p-button label="Resend Code" styleClass="button" [link]="true" class="p-0 !border-none"/>
            <p-button label="Submit Code" styleClass="button" class="cursor-pointer"/>
        </div>
    </div>
</div>
